### ISSUE TITLE
🛠 Tooling: Bring in updated conventional-commits-parser types

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/should-semantic-release#174]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/should-semantic-release/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Following https://github.com/JoshuaKGoldberg/should-semantic-release/pull/168#discussion_r1492662292, this repo now has an `as` assertion to work around incorrect `@types/conventional-commits-parser` types:

https://github.com/JoshuaKGoldberg/should-semantic-release/blob/649aad9b203b9e10505079b85558bfdc83c766b8/src/getCommitMeaning.ts#L12-L16

Filing this tracking issue to indicate that once the types are fixed, this repo can stop using an `as`.

**Comment by hyoban** [comment]
Try to create a PR at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68699
