### ISSUE TITLE
🛠 Tooling: new version not published

### ISSUE THREAD

**Issue by hyoban** [JoshuaKGoldberg/should-semantic-release#175]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/should-semantic-release/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Publish a new version to npm.

### Additional Info

Because PR is not merged by `Squash and merge`, the release action stopped.

https://github.com/JoshuaKGoldberg/should-semantic-release/actions/runs/7942879524/job/21686625891#step:5:20

**Comment by JoshuaKGoldberg** [comment]
Ah, thanks - good catch :)

**Comment by JoshuaKGoldberg** [comment]
https://github.com/JoshuaKGoldberg/should-semantic-release/commit/7bad1b26cbdad62bb07464d6987e38634cc5ef1c ✨
